import json
import tempfile
import unittest
from pathlib import Path

from pptx import Presentation

from actions import email_control as email_module
from actions import presentation_maker
from actions import send_message as message_module
from actions.jarvis_file_stamp import (
    mark_created_file,
    reset_active_persona,
    set_active_persona,
    write_text_with_stamp,
)
from main import JarvisLive


class _Client:
    def __init__(self):
        self.on_text_command = None
        self.current_mode = "jarvis"
        self.current_file = None
        self._voice_combo = None
        self.muted = False


class PersonaAttributionTests(unittest.TestCase):
    def test_engine_stamps_authored_arguments_with_active_persona(self):
        engine = JarvisLive(_Client(), "puck")

        for mode, expected in (
            ("jarvis", "CREATED BY JARVIS"),
            ("ultron", "CREATED BY ULTRON"),
            ("atlas", "CREATED BY ATLAS"),
        ):
            engine.persona_mode = mode
            message = {"action": "send", "message_text": "Status received"}
            persona, attribution = engine._attribute_tool_arguments(
                "send_message", message
            )
            self.assertEqual(attribution, expected)
            self.assertEqual(persona, mode.upper())
            self.assertTrue(message["message_text"].endswith(expected))

            email = {"action": "prepare", "body": "Report attached"}
            engine._attribute_tool_arguments("email_control", email)
            self.assertTrue(email["body"].endswith(expected))

    def test_message_footer_replaces_other_persona_without_duplication(self):
        text = message_module._with_persona_footer(
            "Ready.\n\nCREATED BY JARVIS",
            "ULTRON",
        )
        self.assertEqual(text.count("CREATED BY"), 1)
        self.assertTrue(text.endswith("CREATED BY ULTRON"))

    def test_email_draft_keeps_persona_signature(self):
        try:
            result = email_module._prepare_email({
                "to": "operator@example.com",
                "subject": "Update",
                "body": "Portal synchronized",
                "provider": "default",
                "_persona_name": "ATLAS",
            })
            self.assertIn("EMAIL_APPROVAL_REQUIRED", result)
            self.assertTrue(
                email_module._get_pending_email()["body"].endswith("CREATED BY ATLAS")
            )
        finally:
            email_module._clear_pending_email()

    def test_text_and_binary_files_record_active_persona(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "module.py"
            token = set_active_persona("ULTRON")
            try:
                write_text_with_stamp(source, "print('online')\n", "Generated test code")
            finally:
                reset_active_persona(token)
            source_text = source.read_text(encoding="utf-8")
            self.assertIn("# ULTRON FILE PROVENANCE", source_text)
            self.assertIn("# Created by: ULTRON", source_text)
            self.assertNotIn("Generated by JARVIS", source_text)

            binary = root / "render.png"
            binary.write_bytes(b"not-a-real-image")
            mark_created_file(binary, "Generated render", persona="ATLAS")
            metadata = json.loads(
                binary.with_name("render.png.jarvis_meta.json").read_text(encoding="utf-8")
            )
            self.assertEqual(metadata["persona"], "ATLAS")
            self.assertEqual(metadata["attribution"], "CREATED BY ATLAS")

    def test_powerpoint_has_persona_metadata_and_visible_footer(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "portal.pptx"
            deck = Presentation()
            deck.slides.add_slide(deck.slide_layouts[6])
            deck.slides.add_slide(deck.slide_layouts[6])
            deck.save(path)

            presentation_maker._apply_persona_provenance_to_pptx(path, "ATLAS")
            stamped = Presentation(path)
            self.assertTrue(stamped.core_properties.author.startswith("ATLAS for "))
            self.assertEqual(stamped.core_properties.last_modified_by, "ATLAS")
            for slide in stamped.slides:
                footers = [
                    shape for shape in slide.shapes
                    if getattr(shape, "name", "") == "persona-attribution"
                ]
                self.assertEqual(len(footers), 1)
                self.assertEqual(footers[0].text, "CREATED BY ATLAS")


if __name__ == "__main__":
    unittest.main()
