import getpass
import json
import os
import re
from contextvars import ContextVar, Token
from datetime import datetime
from pathlib import Path


STAMP_TITLE = "JARVIS FILE PROVENANCE"
PERSONA_NAMES = frozenset({"JARVIS", "ULTRON", "ATLAS"})
_ACTIVE_PERSONA: ContextVar[str] = ContextVar("jarvis_active_persona", default="JARVIS")
_ATTRIBUTION_RE = re.compile(
    r"(?im)^\s*CREATED BY (?:JARVIS|ULTRON|ATLAS)\s*$"
)

LINE_COMMENT_EXTS = {
    ".py", ".sh", ".bash", ".zsh", ".js", ".jsx", ".ts", ".tsx", ".java",
    ".c", ".h", ".cpp", ".hpp", ".cs", ".go", ".rs", ".rb", ".php", ".swift",
    ".kt", ".kts", ".lua", ".r", ".sql", ".yaml", ".yml", ".toml", ".ini",
    ".cfg", ".conf", ".ps1", ".dockerfile", ".gitignore",
}
HTML_COMMENT_EXTS = {".html", ".htm", ".xml", ".svg"}
CSS_COMMENT_EXTS = {".css", ".scss", ".sass", ".less"}
PLAIN_TEXT_EXTS = {".txt", ".md", ".rst", ".log", ".text"}
EMBEDDABLE_EXTS = LINE_COMMENT_EXTS | HTML_COMMENT_EXTS | CSS_COMMENT_EXTS | PLAIN_TEXT_EXTS


def normalize_persona(persona: str | None = None) -> str:
    value = str(persona or _ACTIVE_PERSONA.get() or "JARVIS").strip().upper()
    return value if value in PERSONA_NAMES else "JARVIS"


def set_active_persona(persona: str) -> Token:
    return _ACTIVE_PERSONA.set(normalize_persona(persona))


def reset_active_persona(token: Token) -> None:
    _ACTIVE_PERSONA.reset(token)


def persona_attribution(persona: str | None = None) -> str:
    return f"CREATED BY {normalize_persona(persona)}"


def append_persona_attribution(text: str, persona: str | None = None) -> str:
    """Append exactly one active-persona signature to authored prose."""
    content = str(text or "").strip()
    attribution = persona_attribution(persona)
    if _ATTRIBUTION_RE.search(content):
        return _ATTRIBUTION_RE.sub(attribution, content).strip()
    return f"{content}\n\n{attribution}" if content else attribution


def generated_by(persona: str | None = None) -> str:
    user = os.environ.get("JARVIS_USER") or getpass.getuser()
    return f"{normalize_persona(persona)} for {user}"


def _timestamp() -> str:
    return datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")


def _context(context: str, persona: str) -> str:
    text = " ".join(str(context or "Generated by JARVIS.").split())
    text = re.sub(r"\bJARVIS\b", normalize_persona(persona), text, flags=re.IGNORECASE)
    return text[:700]


def _metadata(target: Path, context: str, persona: str | None = None) -> dict:
    persona = normalize_persona(persona)
    return {
        "title": f"{persona} FILE PROVENANCE",
        "persona": persona,
        "attribution": persona_attribution(persona),
        "generated_by": generated_by(persona),
        "created_at": _timestamp(),
        "file": target.name,
        "context": _context(context, persona),
    }


def _has_stamp(content: str) -> bool:
    return bool(re.search(
        r"(?:JARVIS|ULTRON|ATLAS) FILE PROVENANCE",
        content[:600],
        flags=re.IGNORECASE,
    ))


def _comment_lines(lines: list[str], marker: str) -> str:
    return "\n".join(f"{marker} {line}".rstrip() for line in lines) + "\n\n"


def stamp_text_content(
    content: str,
    target: Path,
    context: str,
    persona: str | None = None,
) -> str:
    text = str(content or "")
    if _has_stamp(text):
        return text

    meta = _metadata(target, context, persona)
    lines = [
        meta["title"],
        f"Created by: {meta['persona']}",
        f"Generated by: {meta['generated_by']}",
        f"Date: {meta['created_at']}",
        f"File context: {meta['context']}",
    ]
    ext = target.suffix.lower()

    if target.name.lower() == "dockerfile" or ext in LINE_COMMENT_EXTS:
        header = _comment_lines(lines, "#")
    elif ext in HTML_COMMENT_EXTS:
        header = "<!--\n" + "\n".join(lines) + "\n-->\n\n"
    elif ext in CSS_COMMENT_EXTS:
        header = "/*\n" + "\n".join(lines) + "\n*/\n\n"
    else:
        header = "\n".join(lines) + "\n\n"

    return header + text


def can_embed_stamp(target: Path) -> bool:
    return target.suffix.lower() in EMBEDDABLE_EXTS or target.name.lower() == "dockerfile"


def write_text_with_stamp(
    target: Path,
    content: str,
    context: str,
    encoding: str = "utf-8",
    persona: str | None = None,
) -> None:
    if can_embed_stamp(target):
        target.write_text(
            stamp_text_content(content, target, context, persona),
            encoding=encoding,
        )
        return
    target.write_text(str(content or ""), encoding=encoding)
    write_sidecar_metadata(target, context, persona)


def write_sidecar_metadata(
    target: Path,
    context: str,
    persona: str | None = None,
) -> Path:
    sidecar = target.with_name(f"{target.name}.jarvis_meta.json")
    sidecar.write_text(
        json.dumps(_metadata(target, context, persona), indent=2),
        encoding="utf-8",
    )
    return sidecar


def write_directory_metadata(
    target: Path,
    context: str,
    persona: str | None = None,
) -> Path:
    """Write a provenance sidecar without making the new directory non-empty."""
    record = target.with_name(f"{target.name}.jarvis_meta.json")
    record.write_text(
        json.dumps(_metadata(target, context, persona), indent=2),
        encoding="utf-8",
    )
    return record


def mark_created_file(
    target: Path,
    context: str,
    persona: str | None = None,
) -> None:
    if not target.exists() or target.is_dir():
        return
    if can_embed_stamp(target):
        try:
            content = target.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            write_sidecar_metadata(target, context, persona)
            return
        write_text_with_stamp(target, content, context, persona=persona)
        return
    write_sidecar_metadata(target, context, persona)
